In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("vinayaks0n1/ipl-2025")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/vinayaks0n1/ipl-2025/1.archive...

100%|██████████| 7.97k/7.97k [00:00<00:00, 10.7MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/vinayaks0n1/ipl-2025/versions/1

In [2]:
import pandas as pd
df_batters = pd.read_csv("/root/.cache/kagglehub/datasets/vinayaks0n1/ipl-2025/versions/1/IPL2025Batters.csv")
df_bowlers = pd.read_csv("/root/.cache/kagglehub/datasets/vinayaks0n1/ipl-2025/versions/1/IPL2025Bowlers.csv")

In [3]:
df_batters.head()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37

In [4]:
df_bowlers.head()

,Player Name,Team,WKT,MAT,INN,OVR,RUNS,BBI,AVG,ECO,SR,4W,5W
0,Prasidh Krishna,GT,25,15,15,59.0,488,41/4,19.52,8.27,14.16,1,0
1,Noor Ahmad,CSK,24,14,14,50.0,408,18/4,17.00,8.16,12.50,2,0
2,Josh Hazlewood,RCB,22,12,12,44.0,386,33/4,17.54,8.77,12.00,1,0
3,Trent Boult,MI,22,16,16,57.4,517,26/4,23.50,8.96,15.72,1,0
4,Arshdeep Singh,PBKS,21,17,16,58.2,518,16/3,24.66,8.88,16.66,0,0

In [5]:
df_batters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player Name  156 non-null    object
 1   Team         156 non-null    object
 2   Runs         156 non-null    int64
 3   Matches      156 non-null    int64
 4   Inn          156 non-null    int64
 5   No           156 non-null    int64
 6   HS           156 non-null    object
 7   AVG          156 non-null    object
 8   BF           156 non-null    int64
 9   SR           156 non-null    float64
 10  100s         156 non-null    int64
 11  50s          156 non-null    int64
 12  4s           156 non-null    int64
 13  6s           156 non-null    int64
dtypes: float64(1), int64(9), object(4)
memory usage: 17.2+ KB

In [6]:
df_bowlers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player Name  108 non-null    object
 1   Team         108 non-null    object
 2   WKT          108 non-null    int64
 3   MAT          108 non-null    int64
 4   INN          108 non-null    int64
 5   OVR          108 non-null    float64
 6   RUNS         108 non-null    int64
 7   BBI          108 non-null    object
 8   AVG          108 non-null    float64
 9   ECO          108 non-null    float64
 10  SR           108 non-null    float64
 11  4W           108 non-null    int64
 12  5W           108 non-null    int64
dtypes: float64(4), int64(6), object(3)
memory usage: 11.1+ KB

In [ ]:
ipl_merged = pd.merge(

)